// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 22, 17, 55, 15, 535, DateTimeKind.Utc).AddTicks(9243),
                            Description = "Initialize the project with proper folder structure and dependencies",
                            DueDate = new DateTime(2026, 3, 24, 17, 55, 15, 535, DateTimeKind.Utc).AddTicks(9699),
                            IsCompleted = true,
                            Title = "Set up project structure",
                            UpdatedAt = new DateTime(2026, 3, 29, 17, 55, 15, 535, DateTimeKind.Utc).AddTicks(7826)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 23, 17, 55, 15, 536, DateTimeKind.Utc).AddTicks(134),
                            Description = "Create entity models and configure EF Core with InMemory provider",
                            DueDate = new DateTime(2026, 3, 25, 17, 55, 15, 536, DateTimeKind.Utc).AddTicks(135),
                            IsCompleted = true,
                            Title = "Design database schema",
                            UpdatedAt = new DateTime(2026, 3, 29, 17, 55, 15, 536, DateTimeKind.Utc).AddTicks(133)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 25, 17, 55, 15, 536, DateTimeKind.Utc).AddTicks(137),
                            Description = "Build CRUD endpoints following RESTful conventions",
                            DueDate = new DateTime(2026, 3, 30, 17, 55, 15, 536, DateTimeKind.Utc).AddTicks(138),
                            IsCompleted = false,
                            Title = "Implement REST API endpoints",
                            UpdatedAt = new DateTime(2026, 3, 29, 17, 55, 15, 536, DateTimeKind.Utc).AddTicks(137)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 26, 17, 55, 15, 536, DateTimeKind.Utc).AddTicks(140),
                            Description = "Create Angular components for listing and managing tasks",
                            DueDate = new DateTime(2026, 4, 1, 17, 55, 15, 536, DateTimeKind.Utc).AddTicks(140),
                            IsCompleted = false,
                            Title = "Build Angular frontend",
                            UpdatedAt = new DateTime(2026, 3, 29, 17, 55, 15, 536, DateTimeKind.Utc).AddTicks(139)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 27, 17, 55, 15, 536, DateTimeKind.Utc).AddTicks(142),
                            Description = "Add test coverage for service and controller layers",
                            DueDate = new DateTime(2026, 4, 5, 17, 55, 15, 536, DateTimeKind.Utc).AddTicks(142),
                            IsCompleted = false,
                            Title = "Write unit tests",
                            UpdatedAt = new DateTime(2026, 3, 29, 17, 55, 15, 536, DateTimeKind.Utc).AddTicks(141)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
